# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cfg_server_ip.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import db_base.hxx_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='cfg_server_ip.hxx',
  package='',
  serialized_pb=_b('\n\x11\x63\x66g_server_ip.hxx\x1a\x0b\x64\x62_base.hxx\"\x99\x02\n\rCFG_SERVER_IP\x12)\n\x0bserver_type\x18\x01 \x01(\x05\x42\x14\x82\xa6\x1d\x10int(11) NOT NULL\x12\'\n\tserver_id\x18\x02 \x01(\x05\x42\x14\x82\xa6\x1d\x10int(11) NOT NULL\x12\x19\n\x03ip1\x18\x03 \x01(\tB\x0c\x82\xa6\x1d\x08\x63har(32)\x12\x19\n\x03ip2\x18\x04 \x01(\tB\x0c\x82\xa6\x1d\x08\x63har(32)\x12\x19\n\x04port\x18\x05 \x01(\x05\x42\x0b\x82\xa6\x1d\x07int(11):c\x82\xb5\x18\rCFG_SERVER_IP\x8a\xb5\x18NPRIMARY KEY (`server_type`, `server_id` )) ENGINE=InnoDB DEFAULT CHARSET=utf8;B\x02H\x01')
  ,
  dependencies=[db_base.hxx_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_CFG_SERVER_IP = _descriptor.Descriptor(
  name='CFG_SERVER_IP',
  full_name='CFG_SERVER_IP',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='server_type', full_name='CFG_SERVER_IP.server_type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\020int(11) NOT NULL'))),
    _descriptor.FieldDescriptor(
      name='server_id', full_name='CFG_SERVER_IP.server_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\020int(11) NOT NULL'))),
    _descriptor.FieldDescriptor(
      name='ip1', full_name='CFG_SERVER_IP.ip1', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\010char(32)'))),
    _descriptor.FieldDescriptor(
      name='ip2', full_name='CFG_SERVER_IP.ip2', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\010char(32)'))),
    _descriptor.FieldDescriptor(
      name='port', full_name='CFG_SERVER_IP.port', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\007int(11)'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\202\265\030\rCFG_SERVER_IP\212\265\030NPRIMARY KEY (`server_type`, `server_id` )) ENGINE=InnoDB DEFAULT CHARSET=utf8;')),
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=316,
)

DESCRIPTOR.message_types_by_name['CFG_SERVER_IP'] = _CFG_SERVER_IP

CFG_SERVER_IP = _reflection.GeneratedProtocolMessageType('CFG_SERVER_IP', (_message.Message,), dict(
  DESCRIPTOR = _CFG_SERVER_IP,
  __module__ = 'cfg_server_ip.hxx_pb2'
  # @@protoc_insertion_point(class_scope:CFG_SERVER_IP)
  ))
_sym_db.RegisterMessage(CFG_SERVER_IP)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
_CFG_SERVER_IP.fields_by_name['server_type'].has_options = True
_CFG_SERVER_IP.fields_by_name['server_type']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\020int(11) NOT NULL'))
_CFG_SERVER_IP.fields_by_name['server_id'].has_options = True
_CFG_SERVER_IP.fields_by_name['server_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\020int(11) NOT NULL'))
_CFG_SERVER_IP.fields_by_name['ip1'].has_options = True
_CFG_SERVER_IP.fields_by_name['ip1']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\010char(32)'))
_CFG_SERVER_IP.fields_by_name['ip2'].has_options = True
_CFG_SERVER_IP.fields_by_name['ip2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\010char(32)'))
_CFG_SERVER_IP.fields_by_name['port'].has_options = True
_CFG_SERVER_IP.fields_by_name['port']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\007int(11)'))
_CFG_SERVER_IP.has_options = True
_CFG_SERVER_IP._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\202\265\030\rCFG_SERVER_IP\212\265\030NPRIMARY KEY (`server_type`, `server_id` )) ENGINE=InnoDB DEFAULT CHARSET=utf8;'))
# @@protoc_insertion_point(module_scope)
