# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: drop_tpl.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='drop_tpl.hxx',
  package='',
  serialized_pb=_b('\n\x0c\x64rop_tpl.hxx\"I\n\nPBDropInfo\x12\x11\n\tdetail_id\x18\x01 \x01(\x05\x12\r\n\x05times\x18\x02 \x01(\x05\x12\x19\n\x11\x64\x65tail_probaility\x18\x03 \x01(\x05\"7\n\tPBDropTpl\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x1e\n\tdrop_info\x18\x02 \x03(\x0b\x32\x0b.PBDropInfo\"\xab\x01\n\x10PBDropDetailInfo\x12\x0e\n\x06itemid\x18\x01 \x01(\x05\x12\x0c\n\x04\x62ind\x18\x02 \x01(\x05\x12\x12\n\nprobaility\x18\x03 \x01(\x05\x12\x0c\n\x04\x66unc\x18\x04 \x01(\x05\x12\x0e\n\x06param1\x18\x05 \x01(\x05\x12\x0e\n\x06param2\x18\x06 \x01(\x05\x12\x0e\n\x06param3\x18\x07 \x01(\x05\x12\x11\n\tnotice_id\x18\x08 \x01(\x05\x12\x14\n\x0cnotice_scope\x18\t \x01(\x05\"m\n\x0fPBDropDetailTpl\x12\n\n\x02id\x18\x01 \x01(\x05\x12+\n\x10\x64rop_detail_info\x18\x02 \x03(\x0b\x32\x11.PBDropDetailInfo\x12\x12\n\ncheck_type\x18\x03 \x01(\t\x12\r\n\x05parm1\x18\x04 \x01(\x05\"B\n\x0cPBRankReward\x12\x10\n\x08min_rank\x18\x01 \x01(\x05\x12\x10\n\x08max_rank\x18\x02 \x01(\x05\x12\x0e\n\x06reward\x18\x03 \x01(\t\"1\n\x10PBRankRewardList\x12\x1d\n\x06reward\x18\x01 \x03(\x0b\x32\r.PBRankRewardB\x02H\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBDROPINFO = _descriptor.Descriptor(
  name='PBDropInfo',
  full_name='PBDropInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detail_id', full_name='PBDropInfo.detail_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='times', full_name='PBDropInfo.times', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='detail_probaility', full_name='PBDropInfo.detail_probaility', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=89,
)


_PBDROPTPL = _descriptor.Descriptor(
  name='PBDropTpl',
  full_name='PBDropTpl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBDropTpl.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drop_info', full_name='PBDropTpl.drop_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=146,
)


_PBDROPDETAILINFO = _descriptor.Descriptor(
  name='PBDropDetailInfo',
  full_name='PBDropDetailInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='itemid', full_name='PBDropDetailInfo.itemid', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bind', full_name='PBDropDetailInfo.bind', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='probaility', full_name='PBDropDetailInfo.probaility', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='func', full_name='PBDropDetailInfo.func', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param1', full_name='PBDropDetailInfo.param1', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param2', full_name='PBDropDetailInfo.param2', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='param3', full_name='PBDropDetailInfo.param3', index=6,
      number=7, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notice_id', full_name='PBDropDetailInfo.notice_id', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='notice_scope', full_name='PBDropDetailInfo.notice_scope', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=149,
  serialized_end=320,
)


_PBDROPDETAILTPL = _descriptor.Descriptor(
  name='PBDropDetailTpl',
  full_name='PBDropDetailTpl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBDropDetailTpl.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='drop_detail_info', full_name='PBDropDetailTpl.drop_detail_info', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='check_type', full_name='PBDropDetailTpl.check_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='parm1', full_name='PBDropDetailTpl.parm1', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=322,
  serialized_end=431,
)


_PBRANKREWARD = _descriptor.Descriptor(
  name='PBRankReward',
  full_name='PBRankReward',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='min_rank', full_name='PBRankReward.min_rank', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_rank', full_name='PBRankReward.max_rank', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reward', full_name='PBRankReward.reward', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=499,
)


_PBRANKREWARDLIST = _descriptor.Descriptor(
  name='PBRankRewardList',
  full_name='PBRankRewardList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='reward', full_name='PBRankRewardList.reward', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=501,
  serialized_end=550,
)

_PBDROPTPL.fields_by_name['drop_info'].message_type = _PBDROPINFO
_PBDROPDETAILTPL.fields_by_name['drop_detail_info'].message_type = _PBDROPDETAILINFO
_PBRANKREWARDLIST.fields_by_name['reward'].message_type = _PBRANKREWARD
DESCRIPTOR.message_types_by_name['PBDropInfo'] = _PBDROPINFO
DESCRIPTOR.message_types_by_name['PBDropTpl'] = _PBDROPTPL
DESCRIPTOR.message_types_by_name['PBDropDetailInfo'] = _PBDROPDETAILINFO
DESCRIPTOR.message_types_by_name['PBDropDetailTpl'] = _PBDROPDETAILTPL
DESCRIPTOR.message_types_by_name['PBRankReward'] = _PBRANKREWARD
DESCRIPTOR.message_types_by_name['PBRankRewardList'] = _PBRANKREWARDLIST

PBDropInfo = _reflection.GeneratedProtocolMessageType('PBDropInfo', (_message.Message,), dict(
  DESCRIPTOR = _PBDROPINFO,
  __module__ = 'drop_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDropInfo)
  ))
_sym_db.RegisterMessage(PBDropInfo)

PBDropTpl = _reflection.GeneratedProtocolMessageType('PBDropTpl', (_message.Message,), dict(
  DESCRIPTOR = _PBDROPTPL,
  __module__ = 'drop_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDropTpl)
  ))
_sym_db.RegisterMessage(PBDropTpl)

PBDropDetailInfo = _reflection.GeneratedProtocolMessageType('PBDropDetailInfo', (_message.Message,), dict(
  DESCRIPTOR = _PBDROPDETAILINFO,
  __module__ = 'drop_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDropDetailInfo)
  ))
_sym_db.RegisterMessage(PBDropDetailInfo)

PBDropDetailTpl = _reflection.GeneratedProtocolMessageType('PBDropDetailTpl', (_message.Message,), dict(
  DESCRIPTOR = _PBDROPDETAILTPL,
  __module__ = 'drop_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDropDetailTpl)
  ))
_sym_db.RegisterMessage(PBDropDetailTpl)

PBRankReward = _reflection.GeneratedProtocolMessageType('PBRankReward', (_message.Message,), dict(
  DESCRIPTOR = _PBRANKREWARD,
  __module__ = 'drop_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBRankReward)
  ))
_sym_db.RegisterMessage(PBRankReward)

PBRankRewardList = _reflection.GeneratedProtocolMessageType('PBRankRewardList', (_message.Message,), dict(
  DESCRIPTOR = _PBRANKREWARDLIST,
  __module__ = 'drop_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBRankRewardList)
  ))
_sym_db.RegisterMessage(PBRankRewardList)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
