# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pet_skin_suit_tpl.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import module_define.hxx_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pet_skin_suit_tpl.hxx',
  package='',
  serialized_pb=_b('\n\x15pet_skin_suit_tpl.hxx\x1a\x11module_define.hxx\"V\n\x10PBTplPetSkinSuit\x12\n\n\x02id\x18\x01 \x01(\x05\x12%\n\x0bproperty_up\x18\x02 \x03(\x0b\x32\x10.PBBasicProperty\x12\x0f\n\x07skin_id\x18\x03 \x03(\x05\x42\x02H\x01')
  ,
  dependencies=[module_define.hxx_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBTPLPETSKINSUIT = _descriptor.Descriptor(
  name='PBTplPetSkinSuit',
  full_name='PBTplPetSkinSuit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='PBTplPetSkinSuit.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='property_up', full_name='PBTplPetSkinSuit.property_up', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='skin_id', full_name='PBTplPetSkinSuit.skin_id', index=2,
      number=3, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=130,
)

_PBTPLPETSKINSUIT.fields_by_name['property_up'].message_type = module_define.hxx_pb2._PBBASICPROPERTY
DESCRIPTOR.message_types_by_name['PBTplPetSkinSuit'] = _PBTPLPETSKINSUIT

PBTplPetSkinSuit = _reflection.GeneratedProtocolMessageType('PBTplPetSkinSuit', (_message.Message,), dict(
  DESCRIPTOR = _PBTPLPETSKINSUIT,
  __module__ = 'pet_skin_suit_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBTplPetSkinSuit)
  ))
_sym_db.RegisterMessage(PBTplPetSkinSuit)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
