# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: module_gather.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='module_gather.hxx',
  package='',
  serialized_pb=_b('\n\x11module_gather.hxx\"/\n\x1aPBMsgC2SBeginGatherRequest\x12\x11\n\tentity_id\x18\x01 \x01(\x05\"B\n\x1bPBMsgS2CBeginGatherResponse\x12\x10\n\x08ret_code\x18\x01 \x01(\x05\x12\x11\n\tentity_id\x18\x02 \x01(\x05\"1\n\x1cPBMsgS2CGatherBeginBroadcast\x12\x11\n\tentity_id\x18\x01 \x01(\x05\"1\n\x1cPBMsgS2CGatherAbortBroadcast\x12\x11\n\tentity_id\x18\x01 \x01(\x05\"A\n\x1aPBMsgS2CGatherEndBroadcast\x12\x11\n\tentity_id\x18\x01 \x01(\x05\x12\x10\n\x08ret_code\x18\x02 \x01(\x05\")\n\x14PBMsgC2SPickupReport\x12\x11\n\tentity_id\x18\x01 \x01(\x05*\x89\x02\n\x13MSGID_MODULE_GATHER\x12\'\n\"ID_GATHER_C2S_BGEIN_GATHER_REQUEST\x10\x81\x16\x12(\n#ID_GATHER_S2C_BEGIN_GATHER_RESPONSE\x10\x82\x16\x12)\n$ID_GATHER_S2C_GATHER_BEGIN_BROADCAST\x10\x83\x16\x12\'\n\"ID_GATHER_S2C_GATHER_END_BROADCAST\x10\x84\x16\x12)\n$ID_GATHER_S2C_GATHER_ABORT_BROADCAST\x10\x85\x16\x12 \n\x1bID_GATHER_C2S_PICKUP_REPORT\x10\x86\x16\x42\x02H\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_MSGID_MODULE_GATHER = _descriptor.EnumDescriptor(
  name='MSGID_MODULE_GATHER',
  full_name='MSGID_MODULE_GATHER',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ID_GATHER_C2S_BGEIN_GATHER_REQUEST', index=0, number=2817,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_GATHER_S2C_BEGIN_GATHER_RESPONSE', index=1, number=2818,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_GATHER_S2C_GATHER_BEGIN_BROADCAST', index=2, number=2819,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_GATHER_S2C_GATHER_END_BROADCAST', index=3, number=2820,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_GATHER_S2C_GATHER_ABORT_BROADCAST', index=4, number=2821,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ID_GATHER_C2S_PICKUP_REPORT', index=5, number=2822,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=351,
  serialized_end=616,
)
_sym_db.RegisterEnumDescriptor(_MSGID_MODULE_GATHER)

MSGID_MODULE_GATHER = enum_type_wrapper.EnumTypeWrapper(_MSGID_MODULE_GATHER)
ID_GATHER_C2S_BGEIN_GATHER_REQUEST = 2817
ID_GATHER_S2C_BEGIN_GATHER_RESPONSE = 2818
ID_GATHER_S2C_GATHER_BEGIN_BROADCAST = 2819
ID_GATHER_S2C_GATHER_END_BROADCAST = 2820
ID_GATHER_S2C_GATHER_ABORT_BROADCAST = 2821
ID_GATHER_C2S_PICKUP_REPORT = 2822



_PBMSGC2SBEGINGATHERREQUEST = _descriptor.Descriptor(
  name='PBMsgC2SBeginGatherRequest',
  full_name='PBMsgC2SBeginGatherRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='PBMsgC2SBeginGatherRequest.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=68,
)


_PBMSGS2CBEGINGATHERRESPONSE = _descriptor.Descriptor(
  name='PBMsgS2CBeginGatherResponse',
  full_name='PBMsgS2CBeginGatherResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgS2CBeginGatherResponse.ret_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='PBMsgS2CBeginGatherResponse.entity_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=136,
)


_PBMSGS2CGATHERBEGINBROADCAST = _descriptor.Descriptor(
  name='PBMsgS2CGatherBeginBroadcast',
  full_name='PBMsgS2CGatherBeginBroadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='PBMsgS2CGatherBeginBroadcast.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=138,
  serialized_end=187,
)


_PBMSGS2CGATHERABORTBROADCAST = _descriptor.Descriptor(
  name='PBMsgS2CGatherAbortBroadcast',
  full_name='PBMsgS2CGatherAbortBroadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='PBMsgS2CGatherAbortBroadcast.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=238,
)


_PBMSGS2CGATHERENDBROADCAST = _descriptor.Descriptor(
  name='PBMsgS2CGatherEndBroadcast',
  full_name='PBMsgS2CGatherEndBroadcast',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='PBMsgS2CGatherEndBroadcast.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ret_code', full_name='PBMsgS2CGatherEndBroadcast.ret_code', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=305,
)


_PBMSGC2SPICKUPREPORT = _descriptor.Descriptor(
  name='PBMsgC2SPickupReport',
  full_name='PBMsgC2SPickupReport',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='entity_id', full_name='PBMsgC2SPickupReport.entity_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=307,
  serialized_end=348,
)

DESCRIPTOR.message_types_by_name['PBMsgC2SBeginGatherRequest'] = _PBMSGC2SBEGINGATHERREQUEST
DESCRIPTOR.message_types_by_name['PBMsgS2CBeginGatherResponse'] = _PBMSGS2CBEGINGATHERRESPONSE
DESCRIPTOR.message_types_by_name['PBMsgS2CGatherBeginBroadcast'] = _PBMSGS2CGATHERBEGINBROADCAST
DESCRIPTOR.message_types_by_name['PBMsgS2CGatherAbortBroadcast'] = _PBMSGS2CGATHERABORTBROADCAST
DESCRIPTOR.message_types_by_name['PBMsgS2CGatherEndBroadcast'] = _PBMSGS2CGATHERENDBROADCAST
DESCRIPTOR.message_types_by_name['PBMsgC2SPickupReport'] = _PBMSGC2SPICKUPREPORT
DESCRIPTOR.enum_types_by_name['MSGID_MODULE_GATHER'] = _MSGID_MODULE_GATHER

PBMsgC2SBeginGatherRequest = _reflection.GeneratedProtocolMessageType('PBMsgC2SBeginGatherRequest', (_message.Message,), dict(
  DESCRIPTOR = _PBMSGC2SBEGINGATHERREQUEST,
  __module__ = 'module_gather.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBMsgC2SBeginGatherRequest)
  ))
_sym_db.RegisterMessage(PBMsgC2SBeginGatherRequest)

PBMsgS2CBeginGatherResponse = _reflection.GeneratedProtocolMessageType('PBMsgS2CBeginGatherResponse', (_message.Message,), dict(
  DESCRIPTOR = _PBMSGS2CBEGINGATHERRESPONSE,
  __module__ = 'module_gather.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBMsgS2CBeginGatherResponse)
  ))
_sym_db.RegisterMessage(PBMsgS2CBeginGatherResponse)

PBMsgS2CGatherBeginBroadcast = _reflection.GeneratedProtocolMessageType('PBMsgS2CGatherBeginBroadcast', (_message.Message,), dict(
  DESCRIPTOR = _PBMSGS2CGATHERBEGINBROADCAST,
  __module__ = 'module_gather.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBMsgS2CGatherBeginBroadcast)
  ))
_sym_db.RegisterMessage(PBMsgS2CGatherBeginBroadcast)

PBMsgS2CGatherAbortBroadcast = _reflection.GeneratedProtocolMessageType('PBMsgS2CGatherAbortBroadcast', (_message.Message,), dict(
  DESCRIPTOR = _PBMSGS2CGATHERABORTBROADCAST,
  __module__ = 'module_gather.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBMsgS2CGatherAbortBroadcast)
  ))
_sym_db.RegisterMessage(PBMsgS2CGatherAbortBroadcast)

PBMsgS2CGatherEndBroadcast = _reflection.GeneratedProtocolMessageType('PBMsgS2CGatherEndBroadcast', (_message.Message,), dict(
  DESCRIPTOR = _PBMSGS2CGATHERENDBROADCAST,
  __module__ = 'module_gather.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBMsgS2CGatherEndBroadcast)
  ))
_sym_db.RegisterMessage(PBMsgS2CGatherEndBroadcast)

PBMsgC2SPickupReport = _reflection.GeneratedProtocolMessageType('PBMsgC2SPickupReport', (_message.Message,), dict(
  DESCRIPTOR = _PBMSGC2SPICKUPREPORT,
  __module__ = 'module_gather.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBMsgC2SPickupReport)
  ))
_sym_db.RegisterMessage(PBMsgC2SPickupReport)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
