# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ums_role_gate.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import db_base.hxx_pb2
import title_db.hxx_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ums_role_gate.hxx',
  package='',
  serialized_pb=_b('\n\x11ums_role_gate.hxx\x1a\x0b\x64\x62_base.hxx\x1a\x0ctitle_db.hxx\"3\n\nPBDBFriend\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x66riendliness\x18\x02 \x01(\x05\"\x1c\n\tPBDBBlack\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\"2\n\x0bPBDBInviter\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x12\n\nvalid_time\x18\x02 \x01(\x05\"x\n\x10PBRoleFreindData\x12 \n\x0b\x66riend_list\x18\x01 \x03(\x0b\x32\x0b.PBDBFriend\x12\x1e\n\nblack_list\x18\x02 \x03(\x0b\x32\n.PBDBBlack\x12\"\n\x0cinviter_list\x18\x03 \x03(\x0b\x32\x0c.PBDBInviter\"H\n\x0fPBDBGuildInvite\x12\x0f\n\x07role_id\x18\x01 \x01(\x05\x12\x10\n\x08guild_id\x18\x02 \x01(\x05\x12\x12\n\nvalid_time\x18\x03 \x01(\x05\"n\n\x0fPBRoleGuildData\x12%\n\x0binvite_list\x18\x01 \x03(\x0b\x32\x10.PBDBGuildInvite\x12\x18\n\x10leave_guild_time\x18\x02 \x01(\x05\x12\x1a\n\x12total_contribution\x18\x03 \x01(\x05\"\xff\x03\n\rUMS_ROLE_GATE\x12\x31\n\x07role_id\x18\x01 \x01(\x05\x42 \x82\xa6\x1d\x1cint(11) NOT NULL DEFAULT \'0\'\x12\x30\n\x0b\x66riend_data\x18\x02 \x01(\x0b\x32\x11.PBRoleFreindDataB\x08\x82\xa6\x1d\x04\x62lob\x12.\n\nguild_data\x18\x03 \x01(\x0b\x32\x10.PBRoleGuildDataB\x08\x82\xa6\x1d\x04\x62lob\x12\x31\n\x07user_cp\x18\x04 \x01(\x05\x42 \x82\xa6\x1d\x1cint(11) NOT NULL DEFAULT \'0\'\x12\x32\n\ntitle_list\x18\x05 \x01(\x0b\x32\x14.PBRoleTitleGateListB\x08\x82\xa6\x1d\x04\x62lob\x12\x36\n\x0cweek_user_cp\x18\x06 \x01(\x05\x42 \x82\xa6\x1d\x1cint(11) NOT NULL DEFAULT \'0\'\x12U\n\x10\x63harm_title_list\x18\x07 \x01(\x0b\x32\x19.PBRoleCharmTitleGateListB \x82\xa6\x1d\x1cint(11) NOT NULL DEFAULT \'0\':c\x82\xb5\x18\rUMS_ROLE_GATE\x8a\xb5\x18NPRIMARY KEY (`role_id`))ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;B\x02H\x01')
  ,
  dependencies=[db_base.hxx_pb2.DESCRIPTOR,title_db.hxx_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBDBFRIEND = _descriptor.Descriptor(
  name='PBDBFriend',
  full_name='PBDBFriend',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='PBDBFriend.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='friendliness', full_name='PBDBFriend.friendliness', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=99,
)


_PBDBBLACK = _descriptor.Descriptor(
  name='PBDBBlack',
  full_name='PBDBBlack',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='PBDBBlack.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=101,
  serialized_end=129,
)


_PBDBINVITER = _descriptor.Descriptor(
  name='PBDBInviter',
  full_name='PBDBInviter',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='PBDBInviter.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_time', full_name='PBDBInviter.valid_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=131,
  serialized_end=181,
)


_PBROLEFREINDDATA = _descriptor.Descriptor(
  name='PBRoleFreindData',
  full_name='PBRoleFreindData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='friend_list', full_name='PBRoleFreindData.friend_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='black_list', full_name='PBRoleFreindData.black_list', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inviter_list', full_name='PBRoleFreindData.inviter_list', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=183,
  serialized_end=303,
)


_PBDBGUILDINVITE = _descriptor.Descriptor(
  name='PBDBGuildInvite',
  full_name='PBDBGuildInvite',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='PBDBGuildInvite.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='guild_id', full_name='PBDBGuildInvite.guild_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='valid_time', full_name='PBDBGuildInvite.valid_time', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=305,
  serialized_end=377,
)


_PBROLEGUILDDATA = _descriptor.Descriptor(
  name='PBRoleGuildData',
  full_name='PBRoleGuildData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='invite_list', full_name='PBRoleGuildData.invite_list', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='leave_guild_time', full_name='PBRoleGuildData.leave_guild_time', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total_contribution', full_name='PBRoleGuildData.total_contribution', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=489,
)


_UMS_ROLE_GATE = _descriptor.Descriptor(
  name='UMS_ROLE_GATE',
  full_name='UMS_ROLE_GATE',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='role_id', full_name='UMS_ROLE_GATE.role_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\034int(11) NOT NULL DEFAULT \'0\''))),
    _descriptor.FieldDescriptor(
      name='friend_data', full_name='UMS_ROLE_GATE.friend_data', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\004blob'))),
    _descriptor.FieldDescriptor(
      name='guild_data', full_name='UMS_ROLE_GATE.guild_data', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\004blob'))),
    _descriptor.FieldDescriptor(
      name='user_cp', full_name='UMS_ROLE_GATE.user_cp', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\034int(11) NOT NULL DEFAULT \'0\''))),
    _descriptor.FieldDescriptor(
      name='title_list', full_name='UMS_ROLE_GATE.title_list', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\004blob'))),
    _descriptor.FieldDescriptor(
      name='week_user_cp', full_name='UMS_ROLE_GATE.week_user_cp', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\034int(11) NOT NULL DEFAULT \'0\''))),
    _descriptor.FieldDescriptor(
      name='charm_title_list', full_name='UMS_ROLE_GATE.charm_title_list', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\034int(11) NOT NULL DEFAULT \'0\''))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\202\265\030\rUMS_ROLE_GATE\212\265\030NPRIMARY KEY (`role_id`))ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;')),
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=492,
  serialized_end=1003,
)

_PBROLEFREINDDATA.fields_by_name['friend_list'].message_type = _PBDBFRIEND
_PBROLEFREINDDATA.fields_by_name['black_list'].message_type = _PBDBBLACK
_PBROLEFREINDDATA.fields_by_name['inviter_list'].message_type = _PBDBINVITER
_PBROLEGUILDDATA.fields_by_name['invite_list'].message_type = _PBDBGUILDINVITE
_UMS_ROLE_GATE.fields_by_name['friend_data'].message_type = _PBROLEFREINDDATA
_UMS_ROLE_GATE.fields_by_name['guild_data'].message_type = _PBROLEGUILDDATA
_UMS_ROLE_GATE.fields_by_name['title_list'].message_type = title_db.hxx_pb2._PBROLETITLEGATELIST
_UMS_ROLE_GATE.fields_by_name['charm_title_list'].message_type = title_db.hxx_pb2._PBROLECHARMTITLEGATELIST
DESCRIPTOR.message_types_by_name['PBDBFriend'] = _PBDBFRIEND
DESCRIPTOR.message_types_by_name['PBDBBlack'] = _PBDBBLACK
DESCRIPTOR.message_types_by_name['PBDBInviter'] = _PBDBINVITER
DESCRIPTOR.message_types_by_name['PBRoleFreindData'] = _PBROLEFREINDDATA
DESCRIPTOR.message_types_by_name['PBDBGuildInvite'] = _PBDBGUILDINVITE
DESCRIPTOR.message_types_by_name['PBRoleGuildData'] = _PBROLEGUILDDATA
DESCRIPTOR.message_types_by_name['UMS_ROLE_GATE'] = _UMS_ROLE_GATE

PBDBFriend = _reflection.GeneratedProtocolMessageType('PBDBFriend', (_message.Message,), dict(
  DESCRIPTOR = _PBDBFRIEND,
  __module__ = 'ums_role_gate.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDBFriend)
  ))
_sym_db.RegisterMessage(PBDBFriend)

PBDBBlack = _reflection.GeneratedProtocolMessageType('PBDBBlack', (_message.Message,), dict(
  DESCRIPTOR = _PBDBBLACK,
  __module__ = 'ums_role_gate.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDBBlack)
  ))
_sym_db.RegisterMessage(PBDBBlack)

PBDBInviter = _reflection.GeneratedProtocolMessageType('PBDBInviter', (_message.Message,), dict(
  DESCRIPTOR = _PBDBINVITER,
  __module__ = 'ums_role_gate.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDBInviter)
  ))
_sym_db.RegisterMessage(PBDBInviter)

PBRoleFreindData = _reflection.GeneratedProtocolMessageType('PBRoleFreindData', (_message.Message,), dict(
  DESCRIPTOR = _PBROLEFREINDDATA,
  __module__ = 'ums_role_gate.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBRoleFreindData)
  ))
_sym_db.RegisterMessage(PBRoleFreindData)

PBDBGuildInvite = _reflection.GeneratedProtocolMessageType('PBDBGuildInvite', (_message.Message,), dict(
  DESCRIPTOR = _PBDBGUILDINVITE,
  __module__ = 'ums_role_gate.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDBGuildInvite)
  ))
_sym_db.RegisterMessage(PBDBGuildInvite)

PBRoleGuildData = _reflection.GeneratedProtocolMessageType('PBRoleGuildData', (_message.Message,), dict(
  DESCRIPTOR = _PBROLEGUILDDATA,
  __module__ = 'ums_role_gate.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBRoleGuildData)
  ))
_sym_db.RegisterMessage(PBRoleGuildData)

UMS_ROLE_GATE = _reflection.GeneratedProtocolMessageType('UMS_ROLE_GATE', (_message.Message,), dict(
  DESCRIPTOR = _UMS_ROLE_GATE,
  __module__ = 'ums_role_gate.hxx_pb2'
  # @@protoc_insertion_point(class_scope:UMS_ROLE_GATE)
  ))
_sym_db.RegisterMessage(UMS_ROLE_GATE)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
_UMS_ROLE_GATE.fields_by_name['role_id'].has_options = True
_UMS_ROLE_GATE.fields_by_name['role_id']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\034int(11) NOT NULL DEFAULT \'0\''))
_UMS_ROLE_GATE.fields_by_name['friend_data'].has_options = True
_UMS_ROLE_GATE.fields_by_name['friend_data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\004blob'))
_UMS_ROLE_GATE.fields_by_name['guild_data'].has_options = True
_UMS_ROLE_GATE.fields_by_name['guild_data']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\004blob'))
_UMS_ROLE_GATE.fields_by_name['user_cp'].has_options = True
_UMS_ROLE_GATE.fields_by_name['user_cp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\034int(11) NOT NULL DEFAULT \'0\''))
_UMS_ROLE_GATE.fields_by_name['title_list'].has_options = True
_UMS_ROLE_GATE.fields_by_name['title_list']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\004blob'))
_UMS_ROLE_GATE.fields_by_name['week_user_cp'].has_options = True
_UMS_ROLE_GATE.fields_by_name['week_user_cp']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\034int(11) NOT NULL DEFAULT \'0\''))
_UMS_ROLE_GATE.fields_by_name['charm_title_list'].has_options = True
_UMS_ROLE_GATE.fields_by_name['charm_title_list']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\202\246\035\034int(11) NOT NULL DEFAULT \'0\''))
_UMS_ROLE_GATE.has_options = True
_UMS_ROLE_GATE._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('\202\265\030\rUMS_ROLE_GATE\212\265\030NPRIMARY KEY (`role_id`))ENGINE=InnoDB DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;'))
# @@protoc_insertion_point(module_scope)
