# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_db.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='task_db.hxx',
  package='',
  serialized_pb=_b('\n\x0btask_db.hxx\"3\n\x0ePBDBTaskAccept\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x10\n\x08progress\x18\x02 \x03(\x05\"8\n\x0fPBDBTaskHistory\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\x14\n\x0c\x63ommit_times\x18\x02 \x01(\x05\"?\n\x12PBDBTaskSubRandRet\x12\x14\n\x0ctask_loop_id\x18\x01 \x01(\x05\x12\x13\n\x0btask_sub_id\x18\x02 \x01(\x05\"\x88\x01\n\x08PBDBTask\x12$\n\x0btask_accept\x18\x01 \x03(\x0b\x32\x0f.PBDBTaskAccept\x12&\n\x0ctask_history\x18\x02 \x03(\x0b\x32\x10.PBDBTaskHistory\x12.\n\x11task_sub_rand_ret\x18\x03 \x03(\x0b\x32\x13.PBDBTaskSubRandRetB\x02H\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBDBTASKACCEPT = _descriptor.Descriptor(
  name='PBDBTaskAccept',
  full_name='PBDBTaskAccept',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='PBDBTaskAccept.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='progress', full_name='PBDBTaskAccept.progress', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=66,
)


_PBDBTASKHISTORY = _descriptor.Descriptor(
  name='PBDBTaskHistory',
  full_name='PBDBTaskHistory',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_id', full_name='PBDBTaskHistory.task_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='commit_times', full_name='PBDBTaskHistory.commit_times', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=124,
)


_PBDBTASKSUBRANDRET = _descriptor.Descriptor(
  name='PBDBTaskSubRandRet',
  full_name='PBDBTaskSubRandRet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_loop_id', full_name='PBDBTaskSubRandRet.task_loop_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_sub_id', full_name='PBDBTaskSubRandRet.task_sub_id', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=189,
)


_PBDBTASK = _descriptor.Descriptor(
  name='PBDBTask',
  full_name='PBDBTask',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='task_accept', full_name='PBDBTask.task_accept', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_history', full_name='PBDBTask.task_history', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='task_sub_rand_ret', full_name='PBDBTask.task_sub_rand_ret', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=328,
)

_PBDBTASK.fields_by_name['task_accept'].message_type = _PBDBTASKACCEPT
_PBDBTASK.fields_by_name['task_history'].message_type = _PBDBTASKHISTORY
_PBDBTASK.fields_by_name['task_sub_rand_ret'].message_type = _PBDBTASKSUBRANDRET
DESCRIPTOR.message_types_by_name['PBDBTaskAccept'] = _PBDBTASKACCEPT
DESCRIPTOR.message_types_by_name['PBDBTaskHistory'] = _PBDBTASKHISTORY
DESCRIPTOR.message_types_by_name['PBDBTaskSubRandRet'] = _PBDBTASKSUBRANDRET
DESCRIPTOR.message_types_by_name['PBDBTask'] = _PBDBTASK

PBDBTaskAccept = _reflection.GeneratedProtocolMessageType('PBDBTaskAccept', (_message.Message,), dict(
  DESCRIPTOR = _PBDBTASKACCEPT,
  __module__ = 'task_db.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDBTaskAccept)
  ))
_sym_db.RegisterMessage(PBDBTaskAccept)

PBDBTaskHistory = _reflection.GeneratedProtocolMessageType('PBDBTaskHistory', (_message.Message,), dict(
  DESCRIPTOR = _PBDBTASKHISTORY,
  __module__ = 'task_db.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDBTaskHistory)
  ))
_sym_db.RegisterMessage(PBDBTaskHistory)

PBDBTaskSubRandRet = _reflection.GeneratedProtocolMessageType('PBDBTaskSubRandRet', (_message.Message,), dict(
  DESCRIPTOR = _PBDBTASKSUBRANDRET,
  __module__ = 'task_db.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDBTaskSubRandRet)
  ))
_sym_db.RegisterMessage(PBDBTaskSubRandRet)

PBDBTask = _reflection.GeneratedProtocolMessageType('PBDBTask', (_message.Message,), dict(
  DESCRIPTOR = _PBDBTASK,
  __module__ = 'task_db.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBDBTask)
  ))
_sym_db.RegisterMessage(PBDBTask)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
