# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: guild_building_tpl.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='guild_building_tpl.hxx',
  package='',
  serialized_pb=_b('\n\x16guild_building_tpl.hxx\"k\n\x19PBTplGuildBuildingUpgrade\x12\r\n\x05level\x18\x01 \x01(\x05\x12\x16\n\x0eneed_guild_exp\x18\x02 \x01(\x05\x12\x16\n\x0eneed_jtd_level\x18\x03 \x01(\x05\x12\x0f\n\x07\x63onsume\x18\x04 \x01(\x05\"W\n\x1aPBTplGuildBuildingBuilding\x12\x0c\n\x04type\x18\x01 \x01(\x05\x12+\n\x07upgrade\x18\x02 \x03(\x0b\x32\x1a.PBTplGuildBuildingUpgrade\"b\n\x15PBTplGuildBuildingJTD\x12-\n\x08\x62uilding\x18\x01 \x03(\x0b\x32\x1b.PBTplGuildBuildingBuilding\x12\x1a\n\x12main_building_type\x18\x02 \x01(\x05\"a\n\x1bPBTplGuildBuildingJBSDonate\x12\x11\n\tmax_count\x18\x01 \x01(\x05\x12\x15\n\rget_guild_exp\x18\x02 \x01(\x05\x12\x18\n\x10get_guild_assets\x18\x03 \x01(\x05\"d\n\x1bPBTplGuildBuildingJBSCommon\x12\x15\n\rmax_guild_exp\x18\x01 \x01(\x05\x12\x18\n\x10max_guild_assets\x18\x02 \x01(\x05\x12\x14\n\x0crecord_count\x18\x03 \x01(\x05\"\xb1\x01\n\x15PBTplGuildBuildingJBS\x12,\n\x06\x63ommon\x18\x01 \x01(\x0b\x32\x1c.PBTplGuildBuildingJBSCommon\x12\x35\n\x0fordinary_donate\x18\x02 \x01(\x0b\x32\x1c.PBTplGuildBuildingJBSDonate\x12\x33\n\rluxury_donate\x18\x03 \x01(\x0b\x32\x1c.PBTplGuildBuildingJBSDonate\"k\n\x12PBTplGuildBuilding\x12+\n\x0bjuntiandian\x18\x01 \x01(\x0b\x32\x16.PBTplGuildBuildingJTD\x12(\n\x08jubaoshu\x18\x02 \x01(\x0b\x32\x16.PBTplGuildBuildingJBSB\x02H\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBTPLGUILDBUILDINGUPGRADE = _descriptor.Descriptor(
  name='PBTplGuildBuildingUpgrade',
  full_name='PBTplGuildBuildingUpgrade',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='level', full_name='PBTplGuildBuildingUpgrade.level', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='need_guild_exp', full_name='PBTplGuildBuildingUpgrade.need_guild_exp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='need_jtd_level', full_name='PBTplGuildBuildingUpgrade.need_jtd_level', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='consume', full_name='PBTplGuildBuildingUpgrade.consume', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=133,
)


_PBTPLGUILDBUILDINGBUILDING = _descriptor.Descriptor(
  name='PBTplGuildBuildingBuilding',
  full_name='PBTplGuildBuildingBuilding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='PBTplGuildBuildingBuilding.type', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upgrade', full_name='PBTplGuildBuildingBuilding.upgrade', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=222,
)


_PBTPLGUILDBUILDINGJTD = _descriptor.Descriptor(
  name='PBTplGuildBuildingJTD',
  full_name='PBTplGuildBuildingJTD',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='building', full_name='PBTplGuildBuildingJTD.building', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='main_building_type', full_name='PBTplGuildBuildingJTD.main_building_type', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=322,
)


_PBTPLGUILDBUILDINGJBSDONATE = _descriptor.Descriptor(
  name='PBTplGuildBuildingJBSDonate',
  full_name='PBTplGuildBuildingJBSDonate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_count', full_name='PBTplGuildBuildingJBSDonate.max_count', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_guild_exp', full_name='PBTplGuildBuildingJBSDonate.get_guild_exp', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='get_guild_assets', full_name='PBTplGuildBuildingJBSDonate.get_guild_assets', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=421,
)


_PBTPLGUILDBUILDINGJBSCOMMON = _descriptor.Descriptor(
  name='PBTplGuildBuildingJBSCommon',
  full_name='PBTplGuildBuildingJBSCommon',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='max_guild_exp', full_name='PBTplGuildBuildingJBSCommon.max_guild_exp', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='max_guild_assets', full_name='PBTplGuildBuildingJBSCommon.max_guild_assets', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='record_count', full_name='PBTplGuildBuildingJBSCommon.record_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=423,
  serialized_end=523,
)


_PBTPLGUILDBUILDINGJBS = _descriptor.Descriptor(
  name='PBTplGuildBuildingJBS',
  full_name='PBTplGuildBuildingJBS',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='common', full_name='PBTplGuildBuildingJBS.common', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ordinary_donate', full_name='PBTplGuildBuildingJBS.ordinary_donate', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='luxury_donate', full_name='PBTplGuildBuildingJBS.luxury_donate', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=526,
  serialized_end=703,
)


_PBTPLGUILDBUILDING = _descriptor.Descriptor(
  name='PBTplGuildBuilding',
  full_name='PBTplGuildBuilding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='juntiandian', full_name='PBTplGuildBuilding.juntiandian', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='jubaoshu', full_name='PBTplGuildBuilding.jubaoshu', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=705,
  serialized_end=812,
)

_PBTPLGUILDBUILDINGBUILDING.fields_by_name['upgrade'].message_type = _PBTPLGUILDBUILDINGUPGRADE
_PBTPLGUILDBUILDINGJTD.fields_by_name['building'].message_type = _PBTPLGUILDBUILDINGBUILDING
_PBTPLGUILDBUILDINGJBS.fields_by_name['common'].message_type = _PBTPLGUILDBUILDINGJBSCOMMON
_PBTPLGUILDBUILDINGJBS.fields_by_name['ordinary_donate'].message_type = _PBTPLGUILDBUILDINGJBSDONATE
_PBTPLGUILDBUILDINGJBS.fields_by_name['luxury_donate'].message_type = _PBTPLGUILDBUILDINGJBSDONATE
_PBTPLGUILDBUILDING.fields_by_name['juntiandian'].message_type = _PBTPLGUILDBUILDINGJTD
_PBTPLGUILDBUILDING.fields_by_name['jubaoshu'].message_type = _PBTPLGUILDBUILDINGJBS
DESCRIPTOR.message_types_by_name['PBTplGuildBuildingUpgrade'] = _PBTPLGUILDBUILDINGUPGRADE
DESCRIPTOR.message_types_by_name['PBTplGuildBuildingBuilding'] = _PBTPLGUILDBUILDINGBUILDING
DESCRIPTOR.message_types_by_name['PBTplGuildBuildingJTD'] = _PBTPLGUILDBUILDINGJTD
DESCRIPTOR.message_types_by_name['PBTplGuildBuildingJBSDonate'] = _PBTPLGUILDBUILDINGJBSDONATE
DESCRIPTOR.message_types_by_name['PBTplGuildBuildingJBSCommon'] = _PBTPLGUILDBUILDINGJBSCOMMON
DESCRIPTOR.message_types_by_name['PBTplGuildBuildingJBS'] = _PBTPLGUILDBUILDINGJBS
DESCRIPTOR.message_types_by_name['PBTplGuildBuilding'] = _PBTPLGUILDBUILDING

PBTplGuildBuildingUpgrade = _reflection.GeneratedProtocolMessageType('PBTplGuildBuildingUpgrade', (_message.Message,), dict(
  DESCRIPTOR = _PBTPLGUILDBUILDINGUPGRADE,
  __module__ = 'guild_building_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBTplGuildBuildingUpgrade)
  ))
_sym_db.RegisterMessage(PBTplGuildBuildingUpgrade)

PBTplGuildBuildingBuilding = _reflection.GeneratedProtocolMessageType('PBTplGuildBuildingBuilding', (_message.Message,), dict(
  DESCRIPTOR = _PBTPLGUILDBUILDINGBUILDING,
  __module__ = 'guild_building_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBTplGuildBuildingBuilding)
  ))
_sym_db.RegisterMessage(PBTplGuildBuildingBuilding)

PBTplGuildBuildingJTD = _reflection.GeneratedProtocolMessageType('PBTplGuildBuildingJTD', (_message.Message,), dict(
  DESCRIPTOR = _PBTPLGUILDBUILDINGJTD,
  __module__ = 'guild_building_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBTplGuildBuildingJTD)
  ))
_sym_db.RegisterMessage(PBTplGuildBuildingJTD)

PBTplGuildBuildingJBSDonate = _reflection.GeneratedProtocolMessageType('PBTplGuildBuildingJBSDonate', (_message.Message,), dict(
  DESCRIPTOR = _PBTPLGUILDBUILDINGJBSDONATE,
  __module__ = 'guild_building_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBTplGuildBuildingJBSDonate)
  ))
_sym_db.RegisterMessage(PBTplGuildBuildingJBSDonate)

PBTplGuildBuildingJBSCommon = _reflection.GeneratedProtocolMessageType('PBTplGuildBuildingJBSCommon', (_message.Message,), dict(
  DESCRIPTOR = _PBTPLGUILDBUILDINGJBSCOMMON,
  __module__ = 'guild_building_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBTplGuildBuildingJBSCommon)
  ))
_sym_db.RegisterMessage(PBTplGuildBuildingJBSCommon)

PBTplGuildBuildingJBS = _reflection.GeneratedProtocolMessageType('PBTplGuildBuildingJBS', (_message.Message,), dict(
  DESCRIPTOR = _PBTPLGUILDBUILDINGJBS,
  __module__ = 'guild_building_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBTplGuildBuildingJBS)
  ))
_sym_db.RegisterMessage(PBTplGuildBuildingJBS)

PBTplGuildBuilding = _reflection.GeneratedProtocolMessageType('PBTplGuildBuilding', (_message.Message,), dict(
  DESCRIPTOR = _PBTPLGUILDBUILDING,
  __module__ = 'guild_building_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBTplGuildBuilding)
  ))
_sym_db.RegisterMessage(PBTplGuildBuilding)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
