# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: playermode_tpl.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='playermode_tpl.hxx',
  package='',
  serialized_pb=_b('\n\x12playermode_tpl.hxx\"c\n\x0fPBPlayerModeTpl\x12$\n\tbase_conf\x18\x01 \x01(\x0b\x32\x11.PBPlayerModeBase\x12*\n\x0ekillvalue_conf\x18\x02 \x01(\x0b\x32\x12.PBPlayerKillValue\"<\n\x10PBPlayerModeBase\x12\x14\n\x0c\x63hangemodelv\x18\x01 \x01(\x05\x12\x12\n\nfreshmanlv\x18\x02 \x01(\x05\"\xa4\x01\n\x11PBPlayerKillValue\x12\x0f\n\x07intored\x18\x01 \x01(\x05\x12\x10\n\x08outtored\x18\x02 \x01(\x05\x12\x14\n\x0cmaxkillpoint\x18\x03 \x01(\x05\x12\x13\n\x0breducepoint\x18\x04 \x01(\x05\x12\x14\n\x0ckillcreature\x18\x05 \x01(\x05\x12+\n\rscene_id_list\x18\x06 \x03(\x0b\x32\x14.PBKillCreatureScene\"K\n\x13PBKillCreatureScene\x12\x10\n\x08scene_id\x18\x01 \x01(\x05\x12\x10\n\x08\x66loor_lv\x18\x02 \x01(\x05\x12\x10\n\x08upper_lv\x18\x03 \x01(\x05\x42\x02H\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PBPLAYERMODETPL = _descriptor.Descriptor(
  name='PBPlayerModeTpl',
  full_name='PBPlayerModeTpl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='base_conf', full_name='PBPlayerModeTpl.base_conf', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='killvalue_conf', full_name='PBPlayerModeTpl.killvalue_conf', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=121,
)


_PBPLAYERMODEBASE = _descriptor.Descriptor(
  name='PBPlayerModeBase',
  full_name='PBPlayerModeBase',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='changemodelv', full_name='PBPlayerModeBase.changemodelv', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='freshmanlv', full_name='PBPlayerModeBase.freshmanlv', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=183,
)


_PBPLAYERKILLVALUE = _descriptor.Descriptor(
  name='PBPlayerKillValue',
  full_name='PBPlayerKillValue',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='intored', full_name='PBPlayerKillValue.intored', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='outtored', full_name='PBPlayerKillValue.outtored', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxkillpoint', full_name='PBPlayerKillValue.maxkillpoint', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='reducepoint', full_name='PBPlayerKillValue.reducepoint', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='killcreature', full_name='PBPlayerKillValue.killcreature', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='scene_id_list', full_name='PBPlayerKillValue.scene_id_list', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=350,
)


_PBKILLCREATURESCENE = _descriptor.Descriptor(
  name='PBKillCreatureScene',
  full_name='PBKillCreatureScene',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scene_id', full_name='PBKillCreatureScene.scene_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='floor_lv', full_name='PBKillCreatureScene.floor_lv', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='upper_lv', full_name='PBKillCreatureScene.upper_lv', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=352,
  serialized_end=427,
)

_PBPLAYERMODETPL.fields_by_name['base_conf'].message_type = _PBPLAYERMODEBASE
_PBPLAYERMODETPL.fields_by_name['killvalue_conf'].message_type = _PBPLAYERKILLVALUE
_PBPLAYERKILLVALUE.fields_by_name['scene_id_list'].message_type = _PBKILLCREATURESCENE
DESCRIPTOR.message_types_by_name['PBPlayerModeTpl'] = _PBPLAYERMODETPL
DESCRIPTOR.message_types_by_name['PBPlayerModeBase'] = _PBPLAYERMODEBASE
DESCRIPTOR.message_types_by_name['PBPlayerKillValue'] = _PBPLAYERKILLVALUE
DESCRIPTOR.message_types_by_name['PBKillCreatureScene'] = _PBKILLCREATURESCENE

PBPlayerModeTpl = _reflection.GeneratedProtocolMessageType('PBPlayerModeTpl', (_message.Message,), dict(
  DESCRIPTOR = _PBPLAYERMODETPL,
  __module__ = 'playermode_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBPlayerModeTpl)
  ))
_sym_db.RegisterMessage(PBPlayerModeTpl)

PBPlayerModeBase = _reflection.GeneratedProtocolMessageType('PBPlayerModeBase', (_message.Message,), dict(
  DESCRIPTOR = _PBPLAYERMODEBASE,
  __module__ = 'playermode_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBPlayerModeBase)
  ))
_sym_db.RegisterMessage(PBPlayerModeBase)

PBPlayerKillValue = _reflection.GeneratedProtocolMessageType('PBPlayerKillValue', (_message.Message,), dict(
  DESCRIPTOR = _PBPLAYERKILLVALUE,
  __module__ = 'playermode_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBPlayerKillValue)
  ))
_sym_db.RegisterMessage(PBPlayerKillValue)

PBKillCreatureScene = _reflection.GeneratedProtocolMessageType('PBKillCreatureScene', (_message.Message,), dict(
  DESCRIPTOR = _PBKILLCREATURESCENE,
  __module__ = 'playermode_tpl.hxx_pb2'
  # @@protoc_insertion_point(class_scope:PBKillCreatureScene)
  ))
_sym_db.RegisterMessage(PBKillCreatureScene)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
