# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service_type.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import code_def.hxx_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='service_type.hxx',
  package='',
  serialized_pb=_b('\n\x10service_type.hxx\x1a\x0c\x63ode_def.hxxB\x02H\x01')
  ,
  dependencies=[code_def.hxx_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
