# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trigger_event.hxx

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='trigger_event.hxx',
  package='',
  serialized_pb=_b('\n\x11trigger_event.hxx*\xa6\x04\n\x11\x45TriggerEventType\x12\x17\n\x13TRIGGER_EVENT_START\x10\x00\x12\x1c\n\x18TRIGGER_EVENT_ENTER_AREA\x10\x01\x12\x1b\n\x17TRIGGER_EVENT_GROUP_DIE\x10\x02\x12\x17\n\x13TRIGGER_EVENT_TIMER\x10\x03\x12$\n TRIGGER_EVENT_CREATURE_DIE_COUNT\x10\x04\x12\x19\n\x15TRIGGER_EVENT_COUNTER\x10\x05\x12\x1c\n\x18TRIGGER_EVENT_AI_2_SCENE\x10\x06\x12\x1e\n\x1aTRIGGER_EVENT_PLAYER_ENTER\x10\x07\x12\x1e\n\x1aTRIGGER_EVENT_PLAYER_LEAVE\x10\x08\x12\x1b\n\x17TRIGGER_EVENT_SCENE_WIN\x10\t\x12\x1c\n\x18TRIGGER_EVENT_SCENE_LOSE\x10\n\x12\x1e\n\x1aTRIGGER_EVENT_FINISH_STORY\x10\x0b\x12\x16\n\x12TRIGGER_EVENT_ITEM\x10\x0c\x12 \n\x1cTRIGGER_EVENT_ACTIVITY_START\x10\r\x12\x1e\n\x1aTRIGGER_EVENT_ACTIVITY_END\x10\x0e\x12\x1c\n\x18TRIGGER_EVENT_GATHER_END\x10\x0f\x12\x19\n\x15TRIGGER_EVENT_TRIGGER\x10\x10\x12\x17\n\x13TRIGGER_EVENT_COUNT\x10\x11\x42\x02H\x01')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

_ETRIGGEREVENTTYPE = _descriptor.EnumDescriptor(
  name='ETriggerEventType',
  full_name='ETriggerEventType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_START', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_ENTER_AREA', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_GROUP_DIE', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_TIMER', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_CREATURE_DIE_COUNT', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_COUNTER', index=5, number=5,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_AI_2_SCENE', index=6, number=6,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_PLAYER_ENTER', index=7, number=7,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_PLAYER_LEAVE', index=8, number=8,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_SCENE_WIN', index=9, number=9,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_SCENE_LOSE', index=10, number=10,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_FINISH_STORY', index=11, number=11,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_ITEM', index=12, number=12,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_ACTIVITY_START', index=13, number=13,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_ACTIVITY_END', index=14, number=14,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_GATHER_END', index=15, number=15,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_TRIGGER', index=16, number=16,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='TRIGGER_EVENT_COUNT', index=17, number=17,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=22,
  serialized_end=572,
)
_sym_db.RegisterEnumDescriptor(_ETRIGGEREVENTTYPE)

ETriggerEventType = enum_type_wrapper.EnumTypeWrapper(_ETRIGGEREVENTTYPE)
TRIGGER_EVENT_START = 0
TRIGGER_EVENT_ENTER_AREA = 1
TRIGGER_EVENT_GROUP_DIE = 2
TRIGGER_EVENT_TIMER = 3
TRIGGER_EVENT_CREATURE_DIE_COUNT = 4
TRIGGER_EVENT_COUNTER = 5
TRIGGER_EVENT_AI_2_SCENE = 6
TRIGGER_EVENT_PLAYER_ENTER = 7
TRIGGER_EVENT_PLAYER_LEAVE = 8
TRIGGER_EVENT_SCENE_WIN = 9
TRIGGER_EVENT_SCENE_LOSE = 10
TRIGGER_EVENT_FINISH_STORY = 11
TRIGGER_EVENT_ITEM = 12
TRIGGER_EVENT_ACTIVITY_START = 13
TRIGGER_EVENT_ACTIVITY_END = 14
TRIGGER_EVENT_GATHER_END = 15
TRIGGER_EVENT_TRIGGER = 16
TRIGGER_EVENT_COUNT = 17


DESCRIPTOR.enum_types_by_name['ETriggerEventType'] = _ETRIGGEREVENTTYPE


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\001'))
# @@protoc_insertion_point(module_scope)
